# Generated by Django 5.2 on 2025-07-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('p_address', models.CharField(max_length=255)),
                ('p_med_issues', models.JSONField(blank=True, default=list)),
                ('p_blood_grp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_dob', models.DateField()),
                ('p_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_date', models.DateField()),
                ('d_time', models.TimeField()),
                ('quantity', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodBank.person')),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_date', models.DateField()),
                ('r_hospital', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('r_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodBank.person')),
            ],
        ),
    ]
